require("core.keymaps")
require("core.options")
require("plugins.blink-cmp")
require("plugins.colorscheme")
require("plugins.oil")
require("plugins.lsp")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.conform")
require("plugins.other")

vim.cmd.colorscheme("vague")
